name: Elevators
version: 1.1
api-version: 1.19
main: me.cxom.elevators.Elevators
description: A Minecraft elevator plugin

commands:
    elevator:
        usage: /elevator <<help|create>|<edit|delete> <elevator>>
        permission: elevator.command
        permission-message: You don't have permission to edit, create, and delete elevators!

permissions:
    elevator.command
