name: Elevators
version: 0.1.5
main: me.cxom.elevators.Elevators
description: A Minecraft elevator plugin

commands:
    elevator:
        usage: /elevator <<help|create>|<edit|delete> <elevator>>